name: Build By Bat

on:
    workflow_dispatch:  # 手动触发工作流

jobs:
  build:
    runs-on: windows-latest  # 运行环境可以是ubuntu, windows, 或 macos

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'  # 设置你使用的Python版本

      # 安装依赖（如果有requirements.txt文件）
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 如果你的项目有依赖，取消注释

      # get.py
      - name: Run get.py
        run: |
          python get.py  # 执行build.py脚本

      # 执行uup_download_windows.cmd
      - name: Run uup_download_windows.cmd
        run: |
          cmd /c uup_download_windows.cmd  # 执行uup_download_windows.cmd脚本
